# Generated by Django 4.0 on 2022-01-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_product_name_alter_product_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Date_Created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Date_created',
            new_name='date_created',
        ),
    ]
